services:
    elasticsearch:
        networks:
            - test_movie_network
        container_name: ${APP_NAME}-elastic
        image: elasticsearch:8.12.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
    db:
        container_name: ${APP_NAME}-db
        image: mariadb:10.6.4-focal
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_TCP_PORT=3306
            - MYSQL_ROOT_PASSWORD=laravelpass
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        ports:
            - 3306:3306
        expose:
            - 3306
            - 33060
        networks:
            - test_movie_network
    webserver:
        image: nginx:alpine
        depends_on:
            - app
        container_name: ${APP_NAME}-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "8081:443"
        volumes:
            - ./app/public:/var/www/public
            - ./app/storage:/var/www/storage
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - test_movie_network
    redis:
        container_name: ${APP_NAME}-redis
        command: redis-server --requirepass test_movie_network
        image: redis:alpine
        ports:
            - 6379:6379
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_PASSWORD=test_movie_network
        networks:
            - test_movie_network
    app:
        container_name: ${APP_NAME}-app
        depends_on:
            - db
        build:
            context: .
            args:
                app_env: ${APP_ENV}
        volumes:
            - ./app:/var/www
        environment:
            # App
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=https://${APP_URL}/
            - APP_BASE_URL=https://${APP_URL}/
            - APP_KEY=${APP_KEY}
            # Database
            - DB_CONNECTION=mysql
            - DB_HOST=${APP_NAME}-db
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - DB_PORT=3306
            # Redis
            - CACHE_DRIVER=redis
            - REDIS_HOST=${APP_NAME}-redis
            - REDIS_PASSWORD=test_movie_network
            - REDIS_PORT=6379
            #Elasticsearch
            - ELASTICSEARCH_HOST="${APP_NAME}-elastic"
            - ELASTICSEARCH_PORT="9200"
            - SCOUT_DRIVER=elastic
        networks:
            - test_movie_network
        restart: unless-stopped
    phpunit:
        image: php:8.1-cli
        container_name: ${APP_NAME}-phpunit
        restart: no
        volumes:
            - ./app:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit
volumes:
    db_data:
networks:
    test_movie_network:
        driver: bridge
